# Generated by Django 5.0.7 on 2024-12-05 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservasi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ACProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Masalah AC",
                "verbose_name_plural": "Masalah AC",
            },
        ),
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Merek Mobil",
                "verbose_name_plural": "Merek Mobil",
            },
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipe Mobil",
                "verbose_name_plural": "Tipe Mobil",
            },
        ),
        migrations.AlterModelOptions(
            name="reservasi",
            options={
                "ordering": ["-tanggal", "-waktu"],
                "verbose_name": "Reservasi",
                "verbose_name_plural": "Reservasi",
            },
        ),
        migrations.AddField(
            model_name="reservasi",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservasi",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservasi",
            name="recommended_service",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reservasi",
            name="layanan",
            field=models.CharField(
                choices=[
                    ("Servis AC", "Servis AC"),
                    ("Isi Freon", "Isi Freon"),
                    ("Pembersihan", "Pembersihan"),
                    ("Perbaikan Komponen", "Perbaikan Komponen"),
                ],
                default="Servis AC",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="reservasi",
            name="status",
            field=models.CharField(
                choices=[
                    ("Dalam Perbaikan", "Dalam Perbaikan"),
                    ("Selesai", "Selesai"),
                    ("Dibatalkan", "Dibatalkan"),
                ],
                default="Dalam Perbaikan",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_service", models.CharField(max_length=100)),
                ("service_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ml_model_used", models.CharField(max_length=50, null=True)),
                ("confidence_score", models.FloatField(null=True)),
                (
                    "car_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservasi.carbrand",
                    ),
                ),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservasi.cartype",
                    ),
                ),
                (
                    "problems",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservasi.acproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekomendasi",
                "verbose_name_plural": "Rekomendasi",
            },
        ),
        migrations.CreateModel(
            name="RecommendationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(null=True)),
                (
                    "current_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_usage",
                        to="reservasi.reservasi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Penggunaan Rekomendasi",
                "verbose_name_plural": "Penggunaan Rekomendasi",
                "unique_together": {("user", "current_reservation")},
            },
        ),
    ]
