# Generated by Django 5.0.7 on 2024-12-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservasi", "0003_reservasi_nominal_pembayaran"),
    ]

    operations = [
        migrations.RemoveField(model_name="recommendation", name="confidence_score",),
        migrations.RemoveField(
            model_name="recommendation", name="recommended_service",
        ),
        migrations.RemoveField(
            model_name="recommendation", name="service_description",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="confidence_scores",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommended_services",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="service_descriptions",
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(model_name="recommendation", name="problems",),
        migrations.AddField(
            model_name="recommendation",
            name="problems",
            field=models.ManyToManyField(to="reservasi.acproblem"),
        ),
    ]
