# Generated by Django 4.2.17 on 2024-12-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservasi", "0005_reservasi_status_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rekomendasi",
                "verbose_name_plural": "Rekomendasi",
            },
        ),
    ]
